### ISSUE TITLE
upgradability

### ISSUE THREAD

**Issue by rayquaza7** [matrixesports/evm-contracts#8]
need upgradability to preserve progress:
what needs to be preserved: 

- [ ] token deleagtion and balances, done through having a separate creator token contract
- [ ] soul bound nfts for win/lose game, can be done by having it as a separate contract
- [ ] dpd for asset?
- [ ] crafting: existing recipes

need to think more about this

**Comment by BoManev** [comment]
Some resources [here](https://www.notion.so/matrixesports/proxy-a65e10ca63b64a5e96904f04e99f6e11)

**Comment by BoManev** [comment]
The proxy pattern decouples state from logic; this allows for a canonical address while supporting versioning of the implementation.
```
User ---- tx ---> Proxy ----------> Implementation_v0
                      |
                      ------------> Implementation_v1
                      |
                      ------------> Implementation_v2
```
The implementation contract code is executed in the context of the proxy state. This has the following side effects:
- storage collisions between proxy and logic or between different active logic versions
  -  [standard storage slots](https://eips.ethereum.org/EIPS/eip-1967)
- proxy selector clashing, collisions between the function selectors in the proxy, and logic 
  -  [transparent proxies](https://docs.openzeppelin.com/contracts/4.x/api/proxy#TransparentUpgradeableProxy)
  -  [uups](https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable)

**Comment by rayquaza7** [comment]
closing for now. dont need upgradability since our contracts are super simple.
